#ifndef CONFIG_H
#define CONFIG_H

/* Define INDI Data Dir */
#cmakedefine INDI_DATA_DIR "@INDI_DATA_DIR@"
/* Define Driver version */
#define MICROSTEPPER_VERSION_MAJOR @MICROSTEPPER_VERSION_MAJOR@
#define MICROSTEPPER_VERSION_MINOR @MICROSTEPPER_VERSION_MINOR@

#endif // CONFIG_H
